### ISSUE TITLE
Unable to refresh partitions in tables with Refresh Policy set

### ISSUE THREAD

**Issue by edhans** [gbrueckl/PowerBI-VSCode#27]
I can refresh a model (calc, full, defrag, etc) and I can refresh a table (calc, full, data, etc), but when I right-click on a partition to refresh, it always fails.

I can refresh the partition in Tabular Editor 3, so it isn't a permission issue. Is this not supported, or is there something else I need to configure in the extension?

**Comment by gbrueckl** [comment]
is the table configured for incremental refresh?
seems like there is an issue with the current implementation where it is not working with incremental refresh
a fix is on the way :)

in the meanwhile you could also use a Power BI Notebook to trigger the refresh - just make sure that you use `"applyRefreshPolicy": false` (that part is missing if you run a refresh via the UI)
```
POST https://api.powerbi.com/v1.0/myorg/groups/aaa070df-9744-4629-96bc-df96da4ff27d/datasets/efecf751-ab1b-48fe-acc6-8fbd9fff1bcb/refreshes
{
	"type":"full",
	"objects":[
		{
			"table":"FactInternetSales",
			"partition":"2021"
		}
	],
	"applyRefreshPolicy": false
}
```

**Comment by samaguire** [comment]
I get the same issue.

Looks to me like the request needs to be adapted to explicitly prevent the refresh policy from being applied when refreshing partitions. By default, it's applied if it's omitted from the request (https://learn.microsoft.com/en-us/power-bi/connect-data/asynchronous-refresh#parameters). A subtle difference between the API and TMSL (in TE3).

You can adapt and run this code in a notebook. The commitMode is optional. I use it due to table size when refreshing. (BTW, it's also super simple to get the API path by right clicking the dataset 😁)

```
POST v1.0/myorg/groups/{groupId}/datasets/{datasetId}/refreshes
{
  "type": "full",
  "commitMode": "partialBatch",
  "applyRefreshPolicy": "false",
  "objects": [
    {
      "table": "SomeTable",
      "partition": "SomePartition1"
    },
    {
      "table": "SomeTable",
      "partition": "SomePartition2"
    }
  ]
}
```
@gbrueckl You may also want to consider allowing the user to input the effectiveDate. If ommitted it defaults to UTC, which for me being UTC+12/13 in NZ can cause issues when incrementing by day. I use the format "yyyy-MM-ddTHH:mm:ss.fffffff".

For completeness, the error message returned from the API
``` json
{
	"startTime": "2024-04-04T08:31:28.323",
	"endTime": "2024-04-04T08:31:28.99",
	"type": "Full",
	"commitMode": "Transactional",
	"status": "Failed",
	"extendedStatus": "Failed",
	"currentRefreshType": "Full",
	"numberOfAttempts": 0,
	"objects": [
		{
			"table": "Transactional",
			"partition": "2022",
			"status": "Failed"
		}
	],
	"messages": [
		{
			"message": "Cannot specify partition for table 'Transactional' having refresh policy defined.",
			"type": "Error"
		}
	]
}
```

**Comment by gbrueckl** [comment]
just published *v1.8.1* that fixes this issue - should be available in the marketplace soon
@samaguire  can you open another ticket for the input of effective date please

**Comment by samaguire** [comment]
> just published _v1.8.1_ that fixes this issue - should be available in the marketplace soon @samaguire can you open another ticket for the input of effective date please

Yip that works for me!

**Comment by edhans** [comment]
Yes, that seems to work. Thanks!

**Comment by gbrueckl** [comment]
great, closing this issue then!
